services:
  
  jira-toolset:
    container_name: jira-toolset
    image: jira-toolset
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./toolset/config:/toolset/config
    restart: unless-stopped